version: "3.9"
services:
  db:
    image: postgres:16
    container_name: cp-postgres
    environment:
      POSTGRES_USER: cp
      POSTGRES_PASSWORD: cp
      POSTGRES_DB: cryptopayroll
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
