spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/cpdb
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

app:
  crypto:
    rpcUrl: http://localhost:8545
    payoutWalletPrivateKey: ${PAYOUT_PK:changeme}
